[2019-02-12 22:01:19,106] INFO [GroupCoordinator 0]: Preparing to rebalance group console-consumer-26867 in state PreparingRebalance with old generation 0 (__consumer_offsets-10) (reason: Adding new member consumer-1-dc399914-2e5b-41c0-8252-23e0bad6df60) (kafka.coordinator.group.GroupCoordinator)
[2019-02-12 22:01:19,107] INFO [GroupCoordinator 0]: Stabilized group console-consumer-26867 generation 1 (__consumer_offsets-10) (kafka.coordinator.group.GroupCoordinator)
[2019-02-12 22:01:19,109] INFO [GroupCoordinator 0]: Assignment received from leader for group console-consumer-26867 for generation 1 (kafka.coordinator.group.GroupCoordinator)
[2019-02-12 22:09:34,969] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-02-12 22:19:34,969] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-02-12 22:29:34,969] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-02-12 22:39:34,969] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-02-12 22:41:13,677] WARN [SocketServer brokerId=0] Unexpected error from /127.0.0.1; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:104)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:381)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:342)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:609)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:541)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
	at kafka.network.Processor.poll(SocketServer.scala:689)
	at kafka.network.Processor.run(SocketServer.scala:594)
	at java.lang.Thread.run(Thread.java:748)
[2019-02-12 22:41:13,679] WARN [SocketServer brokerId=0] Unexpected error from /127.0.0.1; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:104)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:381)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:342)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:609)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:541)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
	at kafka.network.Processor.poll(SocketServer.scala:689)
	at kafka.network.Processor.run(SocketServer.scala:594)
	at java.lang.Thread.run(Thread.java:748)
[2019-02-12 22:41:13,680] WARN [SocketServer brokerId=0] Unexpected error from /127.0.0.1; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:104)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:381)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:342)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:609)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:541)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
	at kafka.network.Processor.poll(SocketServer.scala:689)
	at kafka.network.Processor.run(SocketServer.scala:594)
	at java.lang.Thread.run(Thread.java:748)
[2019-02-12 22:41:13,681] WARN [SocketServer brokerId=0] Unexpected error from /127.0.0.1; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:104)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:381)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:342)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:609)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:541)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
	at kafka.network.Processor.poll(SocketServer.scala:689)
	at kafka.network.Processor.run(SocketServer.scala:594)
	at java.lang.Thread.run(Thread.java:748)
[2019-02-12 22:41:13,681] WARN [SocketServer brokerId=0] Unexpected error from /127.0.0.1; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:104)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:381)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:342)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:609)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:541)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
	at kafka.network.Processor.poll(SocketServer.scala:689)
	at kafka.network.Processor.run(SocketServer.scala:594)
	at java.lang.Thread.run(Thread.java:748)
[2019-02-12 22:41:13,682] WARN [SocketServer brokerId=0] Unexpected error from /127.0.0.1; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:104)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:381)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:342)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:609)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:541)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
	at kafka.network.Processor.poll(SocketServer.scala:689)
	at kafka.network.Processor.run(SocketServer.scala:594)
	at java.lang.Thread.run(Thread.java:748)
[2019-02-12 22:41:13,682] WARN [SocketServer brokerId=0] Unexpected error from /127.0.0.1; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:104)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:381)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:342)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:609)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:541)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
	at kafka.network.Processor.poll(SocketServer.scala:689)
	at kafka.network.Processor.run(SocketServer.scala:594)
	at java.lang.Thread.run(Thread.java:748)
[2019-02-12 22:41:13,683] WARN [SocketServer brokerId=0] Unexpected error from /127.0.0.1; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:104)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:381)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:342)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:609)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:541)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
	at kafka.network.Processor.poll(SocketServer.scala:689)
	at kafka.network.Processor.run(SocketServer.scala:594)
	at java.lang.Thread.run(Thread.java:748)
[2019-02-12 22:41:13,683] WARN [SocketServer brokerId=0] Unexpected error from /127.0.0.1; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:104)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:381)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:342)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:609)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:541)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
	at kafka.network.Processor.poll(SocketServer.scala:689)
	at kafka.network.Processor.run(SocketServer.scala:594)
	at java.lang.Thread.run(Thread.java:748)
[2019-02-12 22:41:13,684] WARN [SocketServer brokerId=0] Unexpected error from /127.0.0.1; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:104)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:381)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:342)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:609)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:541)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
	at kafka.network.Processor.poll(SocketServer.scala:689)
	at kafka.network.Processor.run(SocketServer.scala:594)
	at java.lang.Thread.run(Thread.java:748)
[2019-02-12 22:41:15,135] WARN [SocketServer brokerId=0] Unexpected error from /127.0.0.1; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:104)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:381)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:342)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:609)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:541)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
	at kafka.network.Processor.poll(SocketServer.scala:689)
	at kafka.network.Processor.run(SocketServer.scala:594)
	at java.lang.Thread.run(Thread.java:748)
[2019-02-12 22:41:15,136] WARN [SocketServer brokerId=0] Unexpected error from /127.0.0.1; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:104)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:381)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:342)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:609)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:541)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
	at kafka.network.Processor.poll(SocketServer.scala:689)
	at kafka.network.Processor.run(SocketServer.scala:594)
	at java.lang.Thread.run(Thread.java:748)
[2019-02-12 22:41:15,137] WARN [SocketServer brokerId=0] Unexpected error from /127.0.0.1; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:104)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:381)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:342)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:609)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:541)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
	at kafka.network.Processor.poll(SocketServer.scala:689)
	at kafka.network.Processor.run(SocketServer.scala:594)
	at java.lang.Thread.run(Thread.java:748)
[2019-02-12 22:41:15,138] WARN [SocketServer brokerId=0] Unexpected error from /127.0.0.1; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:104)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:381)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:342)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:609)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:541)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
	at kafka.network.Processor.poll(SocketServer.scala:689)
	at kafka.network.Processor.run(SocketServer.scala:594)
	at java.lang.Thread.run(Thread.java:748)
[2019-02-12 22:41:15,139] WARN [SocketServer brokerId=0] Unexpected error from /127.0.0.1; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:104)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:381)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:342)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:609)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:541)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
	at kafka.network.Processor.poll(SocketServer.scala:689)
	at kafka.network.Processor.run(SocketServer.scala:594)
	at java.lang.Thread.run(Thread.java:748)
[2019-02-12 22:41:15,142] WARN [SocketServer brokerId=0] Unexpected error from /127.0.0.1; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:104)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:381)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:342)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:609)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:541)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
	at kafka.network.Processor.poll(SocketServer.scala:689)
	at kafka.network.Processor.run(SocketServer.scala:594)
	at java.lang.Thread.run(Thread.java:748)
[2019-02-12 22:41:15,143] WARN [SocketServer brokerId=0] Unexpected error from /127.0.0.1; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:104)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:381)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:342)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:609)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:541)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
	at kafka.network.Processor.poll(SocketServer.scala:689)
	at kafka.network.Processor.run(SocketServer.scala:594)
	at java.lang.Thread.run(Thread.java:748)
[2019-02-12 22:41:15,143] WARN [SocketServer brokerId=0] Unexpected error from /127.0.0.1; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:104)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:381)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:342)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:609)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:541)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
	at kafka.network.Processor.poll(SocketServer.scala:689)
	at kafka.network.Processor.run(SocketServer.scala:594)
	at java.lang.Thread.run(Thread.java:748)
[2019-02-12 22:41:15,144] WARN [SocketServer brokerId=0] Unexpected error from /127.0.0.1; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:104)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:381)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:342)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:609)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:541)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
	at kafka.network.Processor.poll(SocketServer.scala:689)
	at kafka.network.Processor.run(SocketServer.scala:594)
	at java.lang.Thread.run(Thread.java:748)
[2019-02-12 22:41:15,144] WARN [SocketServer brokerId=0] Unexpected error from /127.0.0.1; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:104)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:381)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:342)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:609)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:541)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
	at kafka.network.Processor.poll(SocketServer.scala:689)
	at kafka.network.Processor.run(SocketServer.scala:594)
	at java.lang.Thread.run(Thread.java:748)
[2019-02-12 22:41:43,588] INFO Unable to read additional data from server sessionid 0x10000bf455b0000, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:41:44,851] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:41:44,852] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:41:45,769] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:45,772] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2019-02-12 22:41:45,773] INFO [KafkaServer id=0] Starting controlled shutdown (kafka.server.KafkaServer)
[2019-02-12 22:41:46,197] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:41:46,198] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:41:46,302] INFO [ZooKeeperClient] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2019-02-12 22:41:47,727] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:48,116] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:41:48,116] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:41:49,110] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:49,245] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:49,305] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:41:49,306] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:41:50,010] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:50,523] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:50,565] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:50,629] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:50,669] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:50,673] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:50,747] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:50,818] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:50,868] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:50,907] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:50,952] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:50,989] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:51,051] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:51,088] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:51,118] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:51,179] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:51,217] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:51,277] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:51,338] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:51,355] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:41:51,356] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:41:51,391] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:51,430] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:51,502] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:51,569] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:51,619] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:51,681] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:51,738] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:51,807] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:51,866] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:51,911] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:51,969] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:52,006] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:52,042] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:52,094] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:52,137] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:52,188] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:52,225] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:53,204] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:53,337] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:41:53,337] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:41:55,010] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:41:55,011] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:41:56,146] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:41:56,147] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:41:57,355] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:41:57,355] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:41:58,199] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:41:59,286] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:41:59,287] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:00,767] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:00,768] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:02,772] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:02,773] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:03,926] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:03,927] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:04,339] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:42:04,339] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-12 22:42:05,756] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:05,757] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:06,758] INFO [GroupCoordinator 0]: Preparing to rebalance group console-consumer-26867 in state PreparingRebalance with old generation 1 (__consumer_offsets-10) (reason: removing member consumer-1-dc399914-2e5b-41c0-8252-23e0bad6df60 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2019-02-12 22:42:06,758] INFO [GroupCoordinator 0]: Group console-consumer-26867 with generation 2 is now empty (__consumer_offsets-10) (kafka.coordinator.group.GroupCoordinator)
[2019-02-12 22:42:06,944] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:06,945] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:08,617] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:08,618] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:09,833] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:09,834] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:11,766] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:11,767] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:13,352] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:13,353] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:15,340] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:15,341] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:16,565] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:16,566] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:18,174] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:18,174] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:19,436] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:19,437] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:20,912] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:20,913] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:22,108] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:22,109] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:23,282] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:23,283] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:24,611] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:24,611] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:25,951] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:25,952] INFO Socket error occurred: localhost/127.0.0.1:2181: 연결이 거부됨 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:27,751] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:27,752] INFO Socket connection established to localhost/127.0.0.1:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:27,775] INFO Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x10000bf455b0000, negotiated timeout = 6000 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:27,775] INFO [ZooKeeperClient] Connected. (kafka.zookeeper.ZooKeeperClient)
[2019-02-12 22:42:27,799] INFO [KafkaServer id=0] Controlled shutdown succeeded (kafka.server.KafkaServer)
[2019-02-12 22:42:27,804] INFO [/config/changes-event-process-thread]: Shutting down (kafka.common.ZkNodeChangeNotificationListener$ChangeEventProcessThread)
[2019-02-12 22:42:27,804] INFO [/config/changes-event-process-thread]: Shutdown completed (kafka.common.ZkNodeChangeNotificationListener$ChangeEventProcessThread)
[2019-02-12 22:42:27,804] INFO [/config/changes-event-process-thread]: Stopped (kafka.common.ZkNodeChangeNotificationListener$ChangeEventProcessThread)
[2019-02-12 22:42:27,805] INFO [SocketServer brokerId=0] Stopping socket server request processors (kafka.network.SocketServer)
[2019-02-12 22:42:27,814] INFO [SocketServer brokerId=0] Stopped socket server request processors (kafka.network.SocketServer)
[2019-02-12 22:42:27,815] INFO [Kafka Request Handler on Broker 0], shutting down (kafka.server.KafkaRequestHandlerPool)
[2019-02-12 22:42:27,817] INFO [Kafka Request Handler on Broker 0], shut down completely (kafka.server.KafkaRequestHandlerPool)
[2019-02-12 22:42:27,819] INFO [KafkaApi-0] Shutdown complete. (kafka.server.KafkaApis)
[2019-02-12 22:42:27,820] INFO [ExpirationReaper-0-topic]: Shutting down (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2019-02-12 22:42:27,945] INFO [ExpirationReaper-0-topic]: Stopped (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2019-02-12 22:42:27,945] INFO [ExpirationReaper-0-topic]: Shutdown completed (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2019-02-12 22:42:27,950] INFO [TransactionCoordinator id=0] Shutting down. (kafka.coordinator.transaction.TransactionCoordinator)
[2019-02-12 22:42:27,952] INFO [ProducerId Manager 0]: Shutdown complete: last producerId assigned 2000 (kafka.coordinator.transaction.ProducerIdManager)
[2019-02-12 22:42:27,952] INFO [Transaction State Manager 0]: Shutdown complete (kafka.coordinator.transaction.TransactionStateManager)
[2019-02-12 22:42:27,953] INFO [Transaction Marker Channel Manager 0]: Shutting down (kafka.coordinator.transaction.TransactionMarkerChannelManager)
[2019-02-12 22:42:27,953] INFO [Transaction Marker Channel Manager 0]: Stopped (kafka.coordinator.transaction.TransactionMarkerChannelManager)
[2019-02-12 22:42:27,953] INFO [Transaction Marker Channel Manager 0]: Shutdown completed (kafka.coordinator.transaction.TransactionMarkerChannelManager)
[2019-02-12 22:42:27,954] INFO [TransactionCoordinator id=0] Shutdown complete. (kafka.coordinator.transaction.TransactionCoordinator)
[2019-02-12 22:42:27,975] INFO [GroupCoordinator 0]: Shutting down. (kafka.coordinator.group.GroupCoordinator)
[2019-02-12 22:42:27,975] INFO [ExpirationReaper-0-Heartbeat]: Shutting down (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2019-02-12 22:42:28,112] INFO [ExpirationReaper-0-Heartbeat]: Stopped (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2019-02-12 22:42:28,112] INFO [ExpirationReaper-0-Heartbeat]: Shutdown completed (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2019-02-12 22:42:28,113] INFO [ExpirationReaper-0-Rebalance]: Shutting down (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2019-02-12 22:42:28,227] INFO [ExpirationReaper-0-Rebalance]: Stopped (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2019-02-12 22:42:28,228] INFO [ExpirationReaper-0-Rebalance]: Shutdown completed (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2019-02-12 22:42:28,230] INFO [GroupCoordinator 0]: Shutdown complete. (kafka.coordinator.group.GroupCoordinator)
[2019-02-12 22:42:28,232] INFO [ReplicaManager broker=0] Shutting down (kafka.server.ReplicaManager)
[2019-02-12 22:42:28,233] INFO [LogDirFailureHandler]: Shutting down (kafka.server.ReplicaManager$LogDirFailureHandler)
[2019-02-12 22:42:28,233] INFO [LogDirFailureHandler]: Stopped (kafka.server.ReplicaManager$LogDirFailureHandler)
[2019-02-12 22:42:28,233] INFO [LogDirFailureHandler]: Shutdown completed (kafka.server.ReplicaManager$LogDirFailureHandler)
[2019-02-12 22:42:28,235] INFO [ReplicaFetcherManager on broker 0] shutting down (kafka.server.ReplicaFetcherManager)
[2019-02-12 22:42:28,236] INFO [ReplicaFetcherManager on broker 0] shutdown completed (kafka.server.ReplicaFetcherManager)
[2019-02-12 22:42:28,236] INFO [ReplicaAlterLogDirsManager on broker 0] shutting down (kafka.server.ReplicaAlterLogDirsManager)
[2019-02-12 22:42:28,236] INFO [ReplicaAlterLogDirsManager on broker 0] shutdown completed (kafka.server.ReplicaAlterLogDirsManager)
[2019-02-12 22:42:28,236] INFO [ExpirationReaper-0-Fetch]: Shutting down (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2019-02-12 22:42:28,408] INFO [ExpirationReaper-0-Fetch]: Stopped (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2019-02-12 22:42:28,408] INFO [ExpirationReaper-0-Fetch]: Shutdown completed (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2019-02-12 22:42:28,409] INFO [ExpirationReaper-0-Produce]: Shutting down (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2019-02-12 22:42:28,546] INFO [ExpirationReaper-0-Produce]: Stopped (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2019-02-12 22:42:28,546] INFO [ExpirationReaper-0-Produce]: Shutdown completed (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2019-02-12 22:42:28,547] INFO [ExpirationReaper-0-DeleteRecords]: Shutting down (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2019-02-12 22:42:28,746] INFO [ExpirationReaper-0-DeleteRecords]: Stopped (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2019-02-12 22:42:28,746] INFO [ExpirationReaper-0-DeleteRecords]: Shutdown completed (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2019-02-12 22:42:28,782] INFO [ReplicaManager broker=0] Shut down completely (kafka.server.ReplicaManager)
[2019-02-12 22:42:28,783] INFO Shutting down. (kafka.log.LogManager)
[2019-02-12 22:42:28,798] INFO [ProducerStateManager partition=__consumer_offsets-8] Writing producer snapshot at offset 3 (kafka.log.ProducerStateManager)
[2019-02-12 22:42:28,800] INFO [ProducerStateManager partition=__consumer_offsets-4] Writing producer snapshot at offset 3 (kafka.log.ProducerStateManager)
[2019-02-12 22:42:28,801] INFO [ProducerStateManager partition=__consumer_offsets-35] Writing producer snapshot at offset 6 (kafka.log.ProducerStateManager)
[2019-02-12 22:42:28,803] INFO [ProducerStateManager partition=restest-0] Writing producer snapshot at offset 62 (kafka.log.ProducerStateManager)
[2019-02-12 22:42:28,804] INFO [ProducerStateManager partition=test-0] Writing producer snapshot at offset 784 (kafka.log.ProducerStateManager)
[2019-02-12 22:42:28,805] INFO [ProducerStateManager partition=__consumer_offsets-37] Writing producer snapshot at offset 3 (kafka.log.ProducerStateManager)
[2019-02-12 22:42:28,823] INFO [ProducerStateManager partition=__consumer_offsets-10] Writing producer snapshot at offset 2 (kafka.log.ProducerStateManager)
[2019-02-12 22:42:28,823] INFO [ProducerStateManager partition=__consumer_offsets-32] Writing producer snapshot at offset 3 (kafka.log.ProducerStateManager)
[2019-02-12 22:42:28,988] INFO Shutdown complete. (kafka.log.LogManager)
[2019-02-12 22:42:29,003] INFO [ZooKeeperClient] Closing. (kafka.zookeeper.ZooKeeperClient)
[2019-02-12 22:42:29,053] INFO Session: 0x10000bf455b0000 closed (org.apache.zookeeper.ZooKeeper)
[2019-02-12 22:42:29,054] INFO EventThread shut down for session: 0x10000bf455b0000 (org.apache.zookeeper.ClientCnxn)
[2019-02-12 22:42:29,055] INFO [ZooKeeperClient] Closed. (kafka.zookeeper.ZooKeeperClient)
[2019-02-12 22:42:29,055] INFO [ThrottledChannelReaper-Fetch]: Shutting down (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2019-02-12 22:42:29,204] INFO [ThrottledChannelReaper-Fetch]: Stopped (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2019-02-12 22:42:29,204] INFO [ThrottledChannelReaper-Fetch]: Shutdown completed (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2019-02-12 22:42:29,204] INFO [ThrottledChannelReaper-Produce]: Shutting down (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2019-02-12 22:42:30,204] INFO [ThrottledChannelReaper-Produce]: Stopped (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2019-02-12 22:42:30,204] INFO [ThrottledChannelReaper-Produce]: Shutdown completed (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2019-02-12 22:42:30,205] INFO [ThrottledChannelReaper-Request]: Shutting down (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2019-02-12 22:42:31,204] INFO [ThrottledChannelReaper-Request]: Stopped (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2019-02-12 22:42:31,204] INFO [ThrottledChannelReaper-Request]: Shutdown completed (kafka.server.ClientQuotaManager$ThrottledChannelReaper)
[2019-02-12 22:42:31,207] INFO [SocketServer brokerId=0] Shutting down socket server (kafka.network.SocketServer)
[2019-02-12 22:42:31,223] INFO [SocketServer brokerId=0] Shutdown completed (kafka.network.SocketServer)
[2019-02-12 22:42:31,226] INFO [KafkaServer id=0] shut down completed (kafka.server.KafkaServer)
